version: "3.9"

services:
  demo-api:
    container_name: demo-api
    image: demo/api
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:8080
    restart: always